(ns domain.currencies
  "Contains a symbol with a map of currency iso code to currency value for the 20 most traded currencies in the world")

(defn dissoc-unused-attrs [currency]
  (-> currency
      (dissoc :class)
      (dissoc :numericCodeAsString)))

#?(:clj
   (defn all-currencies []
     (into {}
           (map (fn [c]
                  [(.getCurrencyCode c)
                   (dissoc-unused-attrs (bean c))])
                (java.util.Currency/getAvailableCurrencies)))))

(def iso->currency
  {"NZD"
   {:currencyCode          "NZD",
    :defaultFractionDigits 2,
    :displayName           "New Zealand Dollar",
    :numericCode           554,
    :symbol                "NZ$"},
   "SGD"
   {:currencyCode          "SGD",
    :defaultFractionDigits 2,
    :displayName           "Singapore Dollar",
    :numericCode           702,
    :symbol                "SGD"},
   "ANG"
   {:currencyCode          "ANG",
    :defaultFractionDigits 2,
    :displayName           "Netherlands Antillean Guilder",
    :numericCode           532,
    :symbol                "ANG"},
   "USS"
   {:currencyCode          "USS",
    :defaultFractionDigits 2,
    :displayName           "US Dollar (Same day)",
    :numericCode           998,
    :symbol                "USS"},
   "MNT"
   {:currencyCode          "MNT",
    :defaultFractionDigits 2,
    :displayName           "Mongolian Tugrik",
    :numericCode           496,
    :symbol                "MNT"},
   "BIF"
   {:currencyCode          "BIF",
    :defaultFractionDigits 0,
    :displayName           "Burundian Franc",
    :numericCode           108,
    :symbol                "BIF"},
   "BBD"
   {:currencyCode          "BBD",
    :defaultFractionDigits 2,
    :displayName           "Barbadian Dollar",
    :numericCode           52,
    :symbol                "BBD"},
   "HUF"
   {:currencyCode          "HUF",
    :defaultFractionDigits 2,
    :displayName           "Hungarian Forint",
    :numericCode           348,
    :symbol                "HUF"},
   "ERN"
   {:currencyCode          "ERN",
    :defaultFractionDigits 2,
    :displayName           "Eritrean Nakfa",
    :numericCode           232,
    :symbol                "ERN"},
   "AZN"
   {:currencyCode          "AZN",
    :defaultFractionDigits 2,
    :displayName           "Azerbaijani Manat",
    :numericCode           944,
    :symbol                "AZN"},
   "BYN"
   {:currencyCode          "BYN",
    :defaultFractionDigits 2,
    :displayName           "Belarusian Ruble",
    :numericCode           933,
    :symbol                "BYN"},
   "AOA"
   {:currencyCode          "AOA",
    :defaultFractionDigits 2,
    :displayName           "Angolan Kwanza",
    :numericCode           973,
    :symbol                "AOA"},
   "PYG"
   {:currencyCode          "PYG",
    :defaultFractionDigits 0,
    :displayName           "Paraguayan Guarani",
    :numericCode           600,
    :symbol                "PYG"},
   "ATS"
   {:currencyCode          "ATS",
    :defaultFractionDigits 2,
    :displayName           "Austrian Schilling",
    :numericCode           40,
    :symbol                "ATS"},
   "MYR"
   {:currencyCode          "MYR",
    :defaultFractionDigits 2,
    :displayName           "Malaysian Ringgit",
    :numericCode           458,
    :symbol                "MYR"},
   "GYD"
   {:currencyCode          "GYD",
    :defaultFractionDigits 2,
    :displayName           "Guyanaese Dollar",
    :numericCode           328,
    :symbol                "GYD"},
   "VUV"
   {:currencyCode          "VUV",
    :defaultFractionDigits 0,
    :displayName           "Vanuatu Vatu",
    :numericCode           548,
    :symbol                "VUV"},
   "ADP"
   {:currencyCode          "ADP",
    :defaultFractionDigits 0,
    :displayName           "Andorran Peseta",
    :numericCode           20,
    :symbol                "ADP"},
   "SLL"
   {:currencyCode          "SLL",
    :defaultFractionDigits 2,
    :displayName           "Sierra Leonean Leone",
    :numericCode           694,
    :symbol                "SLL"},
   "FKP"
   {:currencyCode          "FKP",
    :defaultFractionDigits 2,
    :displayName           "Falkland Islands Pound",
    :numericCode           238,
    :symbol                "FKP"},
   "DJF"
   {:currencyCode          "DJF",
    :defaultFractionDigits 0,
    :displayName           "Djiboutian Franc",
    :numericCode           262,
    :symbol                "DJF"},
   "BEF"
   {:currencyCode          "BEF",
    :defaultFractionDigits 0,
    :displayName           "Belgian Franc",
    :numericCode           56,
    :symbol                "BEF"},
   "CYP"
   {:currencyCode          "CYP",
    :defaultFractionDigits 2,
    :displayName           "Cypriot Pound",
    :numericCode           196,
    :symbol                "CYP"},
   "GNF"
   {:currencyCode          "GNF",
    :defaultFractionDigits 0,
    :displayName           "Guinean Franc",
    :numericCode           324,
    :symbol                "GNF"},
   "IEP"
   {:currencyCode          "IEP",
    :defaultFractionDigits 2,
    :displayName           "Irish Pound",
    :numericCode           372,
    :symbol                "IEP"},
   "LVL"
   {:currencyCode          "LVL",
    :defaultFractionDigits 2,
    :displayName           "Latvian Lats",
    :numericCode           428,
    :symbol                "LVL"},
   "MMK"
   {:currencyCode          "MMK",
    :defaultFractionDigits 2,
    :displayName           "Myanmar Kyat",
    :numericCode           104,
    :symbol                "MMK"},
   "MRO"
   {:currencyCode          "MRO",
    :defaultFractionDigits 2,
    :displayName           "Mauritanian Ouguiya (1973–2017)",
    :numericCode           478,
    :symbol                "MRO"},
   "RSD"
   {:currencyCode          "RSD",
    :defaultFractionDigits 2,
    :displayName           "Serbian Dinar",
    :numericCode           941,
    :symbol                "RSD"},
   "AYM"
   {:currencyCode          "AYM",
    :defaultFractionDigits 2,
    :displayName           "AYM",
    :numericCode           945,
    :symbol                "AYM"},
   "CLF"
   {:currencyCode          "CLF",
    :defaultFractionDigits 4,
    :displayName           "Chilean Unit of Account (UF)",
    :numericCode           990,
    :symbol                "CLF"},
   "XDR"
   {:currencyCode          "XDR",
    :defaultFractionDigits -1,
    :displayName           "Special Drawing Rights",
    :numericCode           960,
    :symbol                "XDR"},
   "ZAR"
   {:currencyCode          "ZAR",
    :defaultFractionDigits 2,
    :displayName           "South African Rand",
    :numericCode           710,
    :symbol                "ZAR"},
   "TND"
   {:currencyCode          "TND",
    :defaultFractionDigits 3,
    :displayName           "Tunisian Dinar",
    :numericCode           788,
    :symbol                "TND"},
   "PHP"
   {:currencyCode          "PHP",
    :defaultFractionDigits 2,
    :displayName           "Philippine Piso",
    :numericCode           608,
    :symbol                "PHP"},
   "KGS"
   {:currencyCode          "KGS",
    :defaultFractionDigits 2,
    :displayName           "Kyrgystani Som",
    :numericCode           417,
    :symbol                "KGS"},
   "XPD"
   {:currencyCode          "XPD",
    :defaultFractionDigits -1,
    :displayName           "Palladium",
    :numericCode           964,
    :symbol                "XPD"},
   "RON"
   {:currencyCode          "RON",
    :defaultFractionDigits 2,
    :displayName           "Romanian Leu",
    :numericCode           946,
    :symbol                "RON"},
   "RUB"
   {:currencyCode          "RUB",
    :defaultFractionDigits 2,
    :displayName           "Russian Ruble",
    :numericCode           643,
    :symbol                "RUB"},
   "KMF"
   {:currencyCode          "KMF",
    :defaultFractionDigits 0,
    :displayName           "Comorian Franc",
    :numericCode           174,
    :symbol                "KMF"},
   "CHW"
   {:currencyCode          "CHW",
    :defaultFractionDigits 2,
    :displayName           "WIR Franc",
    :numericCode           948,
    :symbol                "CHW"},
   "SCR"
   {:currencyCode          "SCR",
    :defaultFractionDigits 2,
    :displayName           "Seychellois Rupee",
    :numericCode           690,
    :symbol                "SCR"},
   "GIP"
   {:currencyCode          "GIP",
    :defaultFractionDigits 2,
    :displayName           "Gibraltar Pound",
    :numericCode           292,
    :symbol                "GIP"},
   "AZM"
   {:currencyCode          "AZM",
    :defaultFractionDigits 2,
    :displayName           "Azerbaijani Manat (1993–2006)",
    :numericCode           31,
    :symbol                "AZM"},
   "XBC"
   {:currencyCode          "XBC",
    :defaultFractionDigits -1,
    :displayName           "European Unit of Account (XBC)",
    :numericCode           957,
    :symbol                "XBC"},
   "MXV"
   {:currencyCode          "MXV",
    :defaultFractionDigits 2,
    :displayName           "Mexican Investment Unit",
    :numericCode           979,
    :symbol                "MXV"},
   "XXX"
   {:currencyCode          "XXX",
    :defaultFractionDigits -1,
    :displayName           "Unknown Currency",
    :numericCode           999,
    :symbol                "¤"},
   "LUF"
   {:currencyCode          "LUF",
    :defaultFractionDigits 0,
    :displayName           "Luxembourgian Franc",
    :numericCode           442,
    :symbol                "LUF"},
   "TRY"
   {:currencyCode          "TRY",
    :defaultFractionDigits 2,
    :displayName           "Turkish Lira",
    :numericCode           949,
    :symbol                "TRY"},
   "ROL"
   {:currencyCode          "ROL",
    :defaultFractionDigits 2,
    :displayName           "Romanian Leu (1952–2006)",
    :numericCode           946,
    :symbol                "ROL"},
   "UYU"
   {:currencyCode          "UYU",
    :defaultFractionDigits 2,
    :displayName           "Uruguayan Peso",
    :numericCode           858,
    :symbol                "UYU"},
   "CSD"
   {:currencyCode          "CSD",
    :defaultFractionDigits 2,
    :displayName           "Serbian Dinar (2002–2006)",
    :numericCode           891,
    :symbol                "CSD"},
   "XCD"
   {:currencyCode          "XCD",
    :defaultFractionDigits 2,
    :displayName           "East Caribbean Dollar",
    :numericCode           951,
    :symbol                "EC$"},
   "FJD"
   {:currencyCode          "FJD",
    :defaultFractionDigits 2,
    :displayName           "Fijian Dollar",
    :numericCode           242,
    :symbol                "FJD"},
   "GHS"
   {:currencyCode          "GHS",
    :defaultFractionDigits 2,
    :displayName           "Ghanaian Cedi",
    :numericCode           936,
    :symbol                "GHS"},
   "MVR"
   {:currencyCode          "MVR",
    :defaultFractionDigits 2,
    :displayName           "Maldivian Rufiyaa",
    :numericCode           462,
    :symbol                "MVR"},
   "AWG"
   {:currencyCode          "AWG",
    :defaultFractionDigits 2,
    :displayName           "Aruban Florin",
    :numericCode           533,
    :symbol                "AWG"},
   "UGX"
   {:currencyCode          "UGX",
    :defaultFractionDigits 0,
    :displayName           "Ugandan Shilling",
    :numericCode           800,
    :symbol                "UGX"},
   "TOP"
   {:currencyCode          "TOP",
    :defaultFractionDigits 2,
    :displayName           "Tongan Paʻanga",
    :numericCode           776,
    :symbol                "TOP"},
   "CVE"
   {:currencyCode          "CVE",
    :defaultFractionDigits 2,
    :displayName           "Cape Verdean Escudo",
    :numericCode           132,
    :symbol                "CVE"},
   "SRG"
   {:currencyCode          "SRG",
    :defaultFractionDigits 2,
    :displayName           "Surinamese Guilder",
    :numericCode           740,
    :symbol                "SRG"},
   "MKD"
   {:currencyCode          "MKD",
    :defaultFractionDigits 2,
    :displayName           "Macedonian Denar",
    :numericCode           807,
    :symbol                "MKD"},
   "COP"
   {:currencyCode          "COP",
    :defaultFractionDigits 2,
    :displayName           "Colombian Peso",
    :numericCode           170,
    :symbol                "COP"},
   "XFU"
   {:currencyCode          "XFU",
    :defaultFractionDigits -1,
    :displayName           "French UIC-Franc",
    :numericCode           0,
    :symbol                "XFU"},
   "CUC"
   {:currencyCode          "CUC",
    :defaultFractionDigits 2,
    :displayName           "Cuban Convertible Peso",
    :numericCode           931,
    :symbol                "CUC"},
   "GTQ"
   {:currencyCode          "GTQ",
    :defaultFractionDigits 2,
    :displayName           "Guatemalan Quetzal",
    :numericCode           320,
    :symbol                "GTQ"},
   "KZT"
   {:currencyCode          "KZT",
    :defaultFractionDigits 2,
    :displayName           "Kazakhstani Tenge",
    :numericCode           398,
    :symbol                "KZT"},
   "MXN"
   {:currencyCode          "MXN",
    :defaultFractionDigits 2,
    :displayName           "Mexican Peso",
    :numericCode           484,
    :symbol                "MX$"},
   "TPE"
   {:currencyCode          "TPE",
    :defaultFractionDigits 0,
    :displayName           "Timorese Escudo",
    :numericCode           626,
    :symbol                "TPE"},
   "MGA"
   {:currencyCode          "MGA",
    :defaultFractionDigits 2,
    :displayName           "Malagasy Ariary",
    :numericCode           969,
    :symbol                "MGA"},
   "AUD"
   {:currencyCode          "AUD",
    :defaultFractionDigits 2,
    :displayName           "Australian Dollar",
    :numericCode           36,
    :symbol                "A$"},
   "BDT"
   {:currencyCode          "BDT",
    :defaultFractionDigits 2,
    :displayName           "Bangladeshi Taka",
    :numericCode           50,
    :symbol                "BDT"},
   "ISK"
   {:currencyCode          "ISK",
    :defaultFractionDigits 0,
    :displayName           "Icelandic Króna",
    :numericCode           352,
    :symbol                "ISK"},
   "KRW"
   {:currencyCode          "KRW",
    :defaultFractionDigits 0,
    :displayName           "South Korean Won",
    :numericCode           410,
    :symbol                "₩"},
   "DZD"
   {:currencyCode          "DZD",
    :defaultFractionDigits 2,
    :displayName           "Algerian Dinar",
    :numericCode           12,
    :symbol                "DZD"},
   "OMR"
   {:currencyCode          "OMR",
    :defaultFractionDigits 3,
    :displayName           "Omani Rial",
    :numericCode           512,
    :symbol                "OMR"},
   "ZMW"
   {:currencyCode          "ZMW",
    :defaultFractionDigits 2,
    :displayName           "Zambian Kwacha",
    :numericCode           967,
    :symbol                "ZMW"},
   "MOP"
   {:currencyCode          "MOP",
    :defaultFractionDigits 2,
    :displayName           "Macanese Pataca",
    :numericCode           446,
    :symbol                "MOP"},
   "CUP"
   {:currencyCode          "CUP",
    :defaultFractionDigits 2,
    :displayName           "Cuban Peso",
    :numericCode           192,
    :symbol                "CUP"},
   "JPY"
   {:currencyCode          "JPY",
    :defaultFractionDigits 0,
    :displayName           "Japanese Yen",
    :numericCode           392,
    :symbol                "¥"},
   "SHP"
   {:currencyCode          "SHP",
    :defaultFractionDigits 2,
    :displayName           "St. Helena Pound",
    :numericCode           654,
    :symbol                "SHP"},
   "VES"
   {:currencyCode          "VES",
    :defaultFractionDigits 2,
    :displayName           "Venezuelan Bolívar",
    :numericCode           928,
    :symbol                "VES"},
   "LSL"
   {:currencyCode          "LSL",
    :defaultFractionDigits 2,
    :displayName           "Lesotho Loti",
    :numericCode           426,
    :symbol                "LSL"},
   "ETB"
   {:currencyCode          "ETB",
    :defaultFractionDigits 2,
    :displayName           "Ethiopian Birr",
    :numericCode           230,
    :symbol                "ETB"},
   "BWP"
   {:currencyCode          "BWP",
    :defaultFractionDigits 2,
    :displayName           "Botswanan Pula",
    :numericCode           72,
    :symbol                "BWP"},
   "MAD"
   {:currencyCode          "MAD",
    :defaultFractionDigits 2,
    :displayName           "Moroccan Dirham",
    :numericCode           504,
    :symbol                "MAD"},
   "AED"
   {:currencyCode          "AED",
    :defaultFractionDigits 2,
    :displayName           "United Arab Emirates Dirham",
    :numericCode           784,
    :symbol                "AED"},
   "GWP"
   {:currencyCode          "GWP",
    :defaultFractionDigits 2,
    :displayName           "Guinea-Bissau Peso",
    :numericCode           624,
    :symbol                "GWP"},
   "NGN"
   {:currencyCode          "NGN",
    :defaultFractionDigits 2,
    :displayName           "Nigerian Naira",
    :numericCode           566,
    :symbol                "NGN"},
   "BRL"
   {:currencyCode          "BRL",
    :defaultFractionDigits 2,
    :displayName           "Brazilian Real",
    :numericCode           986,
    :symbol                "R$"},
   "BYB"
   {:currencyCode          "BYB",
    :defaultFractionDigits 0,
    :displayName           "Belarusian Ruble (1994–1999)",
    :numericCode           112,
    :symbol                "BYB"},
   "XTS"
   {:currencyCode          "XTS",
    :defaultFractionDigits -1,
    :displayName           "Testing Currency Code",
    :numericCode           963,
    :symbol                "XTS"},
   "GEL"
   {:currencyCode          "GEL",
    :defaultFractionDigits 2,
    :displayName           "Georgian Lari",
    :numericCode           981,
    :symbol                "GEL"},
   "IDR"
   {:currencyCode          "IDR",
    :defaultFractionDigits 2,
    :displayName           "Indonesian Rupiah",
    :numericCode           360,
    :symbol                "IDR"},
   "EUR"
   {:currencyCode          "EUR",
    :defaultFractionDigits 2,
    :displayName           "Euro",
    :numericCode           978,
    :symbol                "€"},
   "GBP"
   {:currencyCode          "GBP",
    :defaultFractionDigits 2,
    :displayName           "British Pound",
    :numericCode           826,
    :symbol                "£"},
   "WST"
   {:currencyCode          "WST",
    :defaultFractionDigits 2,
    :displayName           "Samoan Tala",
    :numericCode           882,
    :symbol                "WST"},
   "UYI"
   {:currencyCode          "UYI",
    :defaultFractionDigits 0,
    :displayName           "Uruguayan Peso (Indexed Units)",
    :numericCode           940,
    :symbol                "UYI"},
   "XAF"
   {:currencyCode          "XAF",
    :defaultFractionDigits 0,
    :displayName           "Central African CFA Franc",
    :numericCode           950,
    :symbol                "FCFA"},
   "SZL"
   {:currencyCode          "SZL",
    :defaultFractionDigits 2,
    :displayName           "Swazi Lilangeni",
    :numericCode           748,
    :symbol                "SZL"},
   "XOF"
   {:currencyCode          "XOF",
    :defaultFractionDigits 0,
    :displayName           "West African CFA Franc",
    :numericCode           952,
    :symbol                "CFA"},
   "SEK"
   {:currencyCode          "SEK",
    :defaultFractionDigits 2,
    :displayName           "Swedish Krona",
    :numericCode           752,
    :symbol                "SEK"},
   "RUR"
   {:currencyCode          "RUR",
    :defaultFractionDigits 2,
    :displayName           "Russian Ruble (1991–1998)",
    :numericCode           810,
    :symbol                "RUR"},
   "SDD"
   {:currencyCode          "SDD",
    :defaultFractionDigits 2,
    :displayName           "Sudanese Dinar (1992–2007)",
    :numericCode           736,
    :symbol                "SDD"},
   "UZS"
   {:currencyCode          "UZS",
    :defaultFractionDigits 2,
    :displayName           "Uzbekistani Som",
    :numericCode           860,
    :symbol                "UZS"},
   "TMM"
   {:currencyCode          "TMM",
    :defaultFractionDigits 2,
    :displayName           "Turkmenistani Manat (1993–2009)",
    :numericCode           795,
    :symbol                "TMM"},
   "KES"
   {:currencyCode          "KES",
    :defaultFractionDigits 2,
    :displayName           "Kenyan Shilling",
    :numericCode           404,
    :symbol                "KES"},
   "KYD"
   {:currencyCode          "KYD",
    :defaultFractionDigits 2,
    :displayName           "Cayman Islands Dollar",
    :numericCode           136,
    :symbol                "KYD"},
   "ILS"
   {:currencyCode          "ILS",
    :defaultFractionDigits 2,
    :displayName           "Israeli New Shekel",
    :numericCode           376,
    :symbol                "₪"},
   "KWD"
   {:currencyCode          "KWD",
    :defaultFractionDigits 3,
    :displayName           "Kuwaiti Dinar",
    :numericCode           414,
    :symbol                "KWD"},
   "NPR"
   {:currencyCode          "NPR",
    :defaultFractionDigits 2,
    :displayName           "Nepalese Rupee",
    :numericCode           524,
    :symbol                "NPR"},
   "MRU"
   {:currencyCode          "MRU",
    :defaultFractionDigits 2,
    :displayName           "Mauritanian Ouguiya",
    :numericCode           929,
    :symbol                "MRU"},
   "BZD"
   {:currencyCode          "BZD",
    :defaultFractionDigits 2,
    :displayName           "Belize Dollar",
    :numericCode           84,
    :symbol                "BZD"},
   "QAR"
   {:currencyCode          "QAR",
    :defaultFractionDigits 2,
    :displayName           "Qatari Rial",
    :numericCode           634,
    :symbol                "QAR"},
   "UAH"
   {:currencyCode          "UAH",
    :defaultFractionDigits 2,
    :displayName           "Ukrainian Hryvnia",
    :numericCode           980,
    :symbol                "UAH"},
   "XSU"
   {:currencyCode          "XSU",
    :defaultFractionDigits -1,
    :displayName           "Sucre",
    :numericCode           994,
    :symbol                "XSU"},
   "BTN"
   {:currencyCode          "BTN",
    :defaultFractionDigits 2,
    :displayName           "Bhutanese Ngultrum",
    :numericCode           64,
    :symbol                "BTN"},
   "HTG"
   {:currencyCode          "HTG",
    :defaultFractionDigits 2,
    :displayName           "Haitian Gourde",
    :numericCode           332,
    :symbol                "HTG"},
   "DKK"
   {:currencyCode          "DKK",
    :defaultFractionDigits 2,
    :displayName           "Danish Krone",
    :numericCode           208,
    :symbol                "DKK"},
   "USN"
   {:currencyCode          "USN",
    :defaultFractionDigits 2,
    :displayName           "US Dollar (Next day)",
    :numericCode           997,
    :symbol                "USN"},
   "VND"
   {:currencyCode          "VND",
    :defaultFractionDigits 0,
    :displayName           "Vietnamese Dong",
    :numericCode           704,
    :symbol                "₫"},
   "SBD"
   {:currencyCode          "SBD",
    :defaultFractionDigits 2,
    :displayName           "Solomon Islands Dollar",
    :numericCode           90,
    :symbol                "SBD"},
   "TRL"
   {:currencyCode          "TRL",
    :defaultFractionDigits 0,
    :displayName           "Turkish Lira (1922–2005)",
    :numericCode           792,
    :symbol                "TRL"},
   "SSP"
   {:currencyCode          "SSP",
    :defaultFractionDigits 2,
    :displayName           "South Sudanese Pound",
    :numericCode           728,
    :symbol                "SSP"},
   "STN"
   {:currencyCode          "STN",
    :defaultFractionDigits 2,
    :displayName           "São Tomé & Príncipe Dobra",
    :numericCode           930,
    :symbol                "STN"},
   "AFA"
   {:currencyCode          "AFA",
    :defaultFractionDigits 2,
    :displayName           "Afghan Afghani (1927–2002)",
    :numericCode           4,
    :symbol                "AFA"},
   "JMD"
   {:currencyCode          "JMD",
    :defaultFractionDigits 2,
    :displayName           "Jamaican Dollar",
    :numericCode           388,
    :symbol                "JMD"},
   "IQD"
   {:currencyCode          "IQD",
    :defaultFractionDigits 3,
    :displayName           "Iraqi Dinar",
    :numericCode           368,
    :symbol                "IQD"},
   "FIM"
   {:currencyCode          "FIM",
    :defaultFractionDigits 2,
    :displayName           "Finnish Markka",
    :numericCode           246,
    :symbol                "FIM"},
   "LBP"
   {:currencyCode          "LBP",
    :defaultFractionDigits 2,
    :displayName           "Lebanese Pound",
    :numericCode           422,
    :symbol                "LBP"},
   "XPT"
   {:currencyCode          "XPT",
    :defaultFractionDigits -1,
    :displayName           "Platinum",
    :numericCode           962,
    :symbol                "XPT"},
   "HRK"
   {:currencyCode          "HRK",
    :defaultFractionDigits 2,
    :displayName           "Croatian Kuna",
    :numericCode           191,
    :symbol                "HRK"},
   "ITL"
   {:currencyCode          "ITL",
    :defaultFractionDigits 0,
    :displayName           "Italian Lira",
    :numericCode           380,
    :symbol                "ITL"},
   "HKD"
   {:currencyCode          "HKD",
    :defaultFractionDigits 2,
    :displayName           "Hong Kong Dollar",
    :numericCode           344,
    :symbol                "HK$"},
   "JOD"
   {:currencyCode          "JOD",
    :defaultFractionDigits 3,
    :displayName           "Jordanian Dinar",
    :numericCode           400,
    :symbol                "JOD"},
   "ZWR"
   {:currencyCode          "ZWR",
    :defaultFractionDigits 2,
    :displayName           "Zimbabwean Dollar (2008)",
    :numericCode           935,
    :symbol                "ZWR"},
   "PAB"
   {:currencyCode          "PAB",
    :defaultFractionDigits 2,
    :displayName           "Panamanian Balboa",
    :numericCode           590,
    :symbol                "PAB"},
   "CDF"
   {:currencyCode          "CDF",
    :defaultFractionDigits 2,
    :displayName           "Congolese Franc",
    :numericCode           976,
    :symbol                "CDF"},
   "VEF"
   {:currencyCode          "VEF",
    :defaultFractionDigits 2,
    :displayName           "Venezuelan Bolívar (2008–2018)",
    :numericCode           937,
    :symbol                "VEF"},
   "XAU"
   {:currencyCode          "XAU",
    :defaultFractionDigits -1,
    :displayName           "Gold",
    :numericCode           959,
    :symbol                "XAU"},
   "MZM"
   {:currencyCode          "MZM",
    :defaultFractionDigits 2,
    :displayName           "Mozambican Metical (1980–2006)",
    :numericCode           508,
    :symbol                "MZM"},
   "BAM"
   {:currencyCode          "BAM",
    :defaultFractionDigits 2,
    :displayName           "Bosnia-Herzegovina Convertible Mark",
    :numericCode           977,
    :symbol                "BAM"},
   "CNY"
   {:currencyCode          "CNY",
    :defaultFractionDigits 2,
    :displayName           "Chinese Yuan",
    :numericCode           156,
    :symbol                "CN¥"},
   "SOS"
   {:currencyCode          "SOS",
    :defaultFractionDigits 2,
    :displayName           "Somali Shilling",
    :numericCode           706,
    :symbol                "SOS"},
   "GRD"
   {:currencyCode          "GRD",
    :defaultFractionDigits 0,
    :displayName           "Greek Drachma",
    :numericCode           300,
    :symbol                "GRD"},
   "XPF"
   {:currencyCode          "XPF",
    :defaultFractionDigits 0,
    :displayName           "CFP Franc",
    :numericCode           953,
    :symbol                "CFPF"},
   "GMD"
   {:currencyCode          "GMD",
    :defaultFractionDigits 2,
    :displayName           "Gambian Dalasi",
    :numericCode           270,
    :symbol                "GMD"},
   "DOP"
   {:currencyCode          "DOP",
    :defaultFractionDigits 2,
    :displayName           "Dominican Peso",
    :numericCode           214,
    :symbol                "DOP"},
   "XAG"
   {:currencyCode          "XAG",
    :defaultFractionDigits -1,
    :displayName           "Silver",
    :numericCode           961,
    :symbol                "XAG"},
   "NLG"
   {:currencyCode          "NLG",
    :defaultFractionDigits 2,
    :displayName           "Dutch Guilder",
    :numericCode           528,
    :symbol                "NLG"},
   "KPW"
   {:currencyCode          "KPW",
    :defaultFractionDigits 2,
    :displayName           "North Korean Won",
    :numericCode           408,
    :symbol                "KPW"},
   "YUM"
   {:currencyCode          "YUM",
    :defaultFractionDigits 2,
    :displayName           "Yugoslavian New Dinar (1994–2002)",
    :numericCode           891,
    :symbol                "YUM"},
   "BOB"
   {:currencyCode          "BOB",
    :defaultFractionDigits 2,
    :displayName           "Bolivian Boliviano",
    :numericCode           68,
    :symbol                "BOB"},
   "BHD"
   {:currencyCode          "BHD",
    :defaultFractionDigits 3,
    :displayName           "Bahraini Dinar",
    :numericCode           48,
    :symbol                "BHD"},
   "BYR"
   {:currencyCode          "BYR",
    :defaultFractionDigits 0,
    :displayName           "Belarusian Ruble (2000–2016)",
    :numericCode           974,
    :symbol                "BYR"},
   "LRD"
   {:currencyCode          "LRD",
    :defaultFractionDigits 2,
    :displayName           "Liberian Dollar",
    :numericCode           430,
    :symbol                "LRD"},
   "BGN"
   {:currencyCode          "BGN",
    :defaultFractionDigits 2,
    :displayName           "Bulgarian Lev",
    :numericCode           975,
    :symbol                "BGN"},
   "AMD"
   {:currencyCode          "AMD",
    :defaultFractionDigits 2,
    :displayName           "Armenian Dram",
    :numericCode           51,
    :symbol                "AMD"},
   "CZK"
   {:currencyCode          "CZK",
    :defaultFractionDigits 2,
    :displayName           "Czech Koruna",
    :numericCode           203,
    :symbol                "CZK"},
   "CAD"
   {:currencyCode          "CAD",
    :defaultFractionDigits 2,
    :displayName           "Canadian Dollar",
    :numericCode           124,
    :symbol                "CA$"},
   "LAK"
   {:currencyCode          "LAK",
    :defaultFractionDigits 2,
    :displayName           "Laotian Kip",
    :numericCode           418,
    :symbol                "LAK"},
   "EEK"
   {:currencyCode          "EEK",
    :defaultFractionDigits 2,
    :displayName           "Estonian Kroon",
    :numericCode           233,
    :symbol                "EEK"},
   "MTL"
   {:currencyCode          "MTL",
    :defaultFractionDigits 2,
    :displayName           "Maltese Lira",
    :numericCode           470,
    :symbol                "MTL"},
   "PLN"
   {:currencyCode          "PLN",
    :defaultFractionDigits 2,
    :displayName           "Polish Zloty",
    :numericCode           985,
    :symbol                "PLN"},
   "LKR"
   {:currencyCode          "LKR",
    :defaultFractionDigits 2,
    :displayName           "Sri Lankan Rupee",
    :numericCode           144,
    :symbol                "LKR"},
   "XUA"
   {:currencyCode          "XUA",
    :defaultFractionDigits -1,
    :displayName           "ADB Unit of Account",
    :numericCode           965,
    :symbol                "XUA"},
   "ESP"
   {:currencyCode          "ESP",
    :defaultFractionDigits 0,
    :displayName           "Spanish Peseta",
    :numericCode           724,
    :symbol                "ESP"},
   "MWK"
   {:currencyCode          "MWK",
    :defaultFractionDigits 2,
    :displayName           "Malawian Kwacha",
    :numericCode           454,
    :symbol                "MWK"},
   "LTL"
   {:currencyCode          "LTL",
    :defaultFractionDigits 2,
    :displayName           "Lithuanian Litas",
    :numericCode           440,
    :symbol                "LTL"},
   "ZMK"
   {:currencyCode          "ZMK",
    :defaultFractionDigits 2,
    :displayName           "Zambian Kwacha (1968–2012)",
    :numericCode           894,
    :symbol                "ZMK"},
   "PGK"
   {:currencyCode          "PGK",
    :defaultFractionDigits 2,
    :displayName           "Papua New Guinean Kina",
    :numericCode           598,
    :symbol                "PGK"},
   "YER"
   {:currencyCode          "YER",
    :defaultFractionDigits 2,
    :displayName           "Yemeni Rial",
    :numericCode           886,
    :symbol                "YER"},
   "PEN"
   {:currencyCode          "PEN",
    :defaultFractionDigits 2,
    :displayName           "Peruvian Sol",
    :numericCode           604,
    :symbol                "PEN"},
   "KHR"
   {:currencyCode          "KHR",
    :defaultFractionDigits 2,
    :displayName           "Cambodian Riel",
    :numericCode           116,
    :symbol                "KHR"},
   "RWF"
   {:currencyCode          "RWF",
    :defaultFractionDigits 0,
    :displayName           "Rwandan Franc",
    :numericCode           646,
    :symbol                "RWF"},
   "BSD"
   {:currencyCode          "BSD",
    :defaultFractionDigits 2,
    :displayName           "Bahamian Dollar",
    :numericCode           44,
    :symbol                "BSD"},
   "SIT"
   {:currencyCode          "SIT",
    :defaultFractionDigits 2,
    :displayName           "Slovenian Tolar",
    :numericCode           705,
    :symbol                "SIT"},
   "XBA"
   {:currencyCode          "XBA",
    :defaultFractionDigits -1,
    :displayName           "European Composite Unit",
    :numericCode           955,
    :symbol                "XBA"},
   "AFN"
   {:currencyCode          "AFN",
    :defaultFractionDigits 2,
    :displayName           "Afghan Afghani",
    :numericCode           971,
    :symbol                "AFN"},
   "ZWL"
   {:currencyCode          "ZWL",
    :defaultFractionDigits 2,
    :displayName           "Zimbabwean Dollar (2009)",
    :numericCode           932,
    :symbol                "ZWL"},
   "ZWD"
   {:currencyCode          "ZWD",
    :defaultFractionDigits 2,
    :displayName           "Zimbabwean Dollar (1980–2008)",
    :numericCode           716,
    :symbol                "ZWD"},
   "MGF"
   {:currencyCode          "MGF",
    :defaultFractionDigits 0,
    :displayName           "Malagasy Franc",
    :numericCode           450,
    :symbol                "MGF"},
   "LYD"
   {:currencyCode          "LYD",
    :defaultFractionDigits 3,
    :displayName           "Libyan Dinar",
    :numericCode           434,
    :symbol                "LYD"},
   "DEM"
   {:currencyCode          "DEM",
    :defaultFractionDigits 2,
    :displayName           "German Mark",
    :numericCode           276,
    :symbol                "DEM"},
   "TMT"
   {:currencyCode          "TMT",
    :defaultFractionDigits 2,
    :displayName           "Turkmenistani Manat",
    :numericCode           934,
    :symbol                "TMT"},
   "HNL"
   {:currencyCode          "HNL",
    :defaultFractionDigits 2,
    :displayName           "Honduran Lempira",
    :numericCode           340,
    :symbol                "HNL"},
   "VEB"
   {:currencyCode          "VEB",
    :defaultFractionDigits 2,
    :displayName           "Venezuelan Bolívar (1871–2008)",
    :numericCode           862,
    :symbol                "VEB"},
   "TWD"
   {:currencyCode          "TWD",
    :defaultFractionDigits 2,
    :displayName           "New Taiwan Dollar",
    :numericCode           901,
    :symbol                "NT$"},
   "XBB"
   {:currencyCode          "XBB",
    :defaultFractionDigits -1,
    :displayName           "European Monetary Unit",
    :numericCode           956,
    :symbol                "XBB"},
   "BGL"
   {:currencyCode          "BGL",
    :defaultFractionDigits 2,
    :displayName           "Bulgarian Hard Lev",
    :numericCode           100,
    :symbol                "BGL"},
   "IRR"
   {:currencyCode          "IRR",
    :defaultFractionDigits 2,
    :displayName           "Iranian Rial",
    :numericCode           364,
    :symbol                "IRR"},
   "MUR"
   {:currencyCode          "MUR",
    :defaultFractionDigits 2,
    :displayName           "Mauritian Rupee",
    :numericCode           480,
    :symbol                "MUR"},
   "BOV"
   {:currencyCode          "BOV",
    :defaultFractionDigits 2,
    :displayName           "Bolivian Mvdol",
    :numericCode           984,
    :symbol                "BOV"},
   "THB"
   {:currencyCode          "THB",
    :defaultFractionDigits 2,
    :displayName           "Thai Baht",
    :numericCode           764,
    :symbol                "THB"},
   "ALL"
   {:currencyCode          "ALL",
    :defaultFractionDigits 2,
    :displayName           "Albanian Lek",
    :numericCode           8,
    :symbol                "ALL"},
   "XBD"
   {:currencyCode          "XBD",
    :defaultFractionDigits -1,
    :displayName           "European Unit of Account (XBD)",
    :numericCode           958,
    :symbol                "XBD"},
   "TJS"
   {:currencyCode          "TJS",
    :defaultFractionDigits 2,
    :displayName           "Tajikistani Somoni",
    :numericCode           972,
    :symbol                "TJS"},
   "SDG"
   {:currencyCode          "SDG",
    :defaultFractionDigits 2,
    :displayName           "Sudanese Pound",
    :numericCode           938,
    :symbol                "SDG"},
   "BMD"
   {:currencyCode          "BMD",
    :defaultFractionDigits 2,
    :displayName           "Bermudan Dollar",
    :numericCode           60,
    :symbol                "BMD"},
   "XFO"
   {:currencyCode          "XFO",
    :defaultFractionDigits -1,
    :displayName           "French Gold Franc",
    :numericCode           0,
    :symbol                "XFO"},
   "CRC"
   {:currencyCode          "CRC",
    :defaultFractionDigits 2,
    :displayName           "Costa Rican Colón",
    :numericCode           188,
    :symbol                "CRC"},
   "USD"
   {:currencyCode          "USD",
    :defaultFractionDigits 2,
    :displayName           "US Dollar",
    :numericCode           840,
    :symbol                "$"},
   "NOK"
   {:currencyCode          "NOK",
    :defaultFractionDigits 2,
    :displayName           "Norwegian Krone",
    :numericCode           578,
    :symbol                "NOK"},
   "SRD"
   {:currencyCode          "SRD",
    :defaultFractionDigits 2,
    :displayName           "Surinamese Dollar",
    :numericCode           968,
    :symbol                "SRD"},
   "MZN"
   {:currencyCode          "MZN",
    :defaultFractionDigits 2,
    :displayName           "Mozambican Metical",
    :numericCode           943,
    :symbol                "MZN"},
   "CLP"
   {:currencyCode          "CLP",
    :defaultFractionDigits 0,
    :displayName           "Chilean Peso",
    :numericCode           152,
    :symbol                "CLP"},
   "STD"
   {:currencyCode          "STD",
    :defaultFractionDigits 2,
    :displayName           "São Tomé & Príncipe Dobra (1977–2017)",
    :numericCode           678,
    :symbol                "STD"},
   "SYP"
   {:currencyCode          "SYP",
    :defaultFractionDigits 2,
    :displayName           "Syrian Pound",
    :numericCode           760,
    :symbol                "SYP"},
   "TZS"
   {:currencyCode          "TZS",
    :defaultFractionDigits 2,
    :displayName           "Tanzanian Shilling",
    :numericCode           834,
    :symbol                "TZS"},
   "EGP"
   {:currencyCode          "EGP",
    :defaultFractionDigits 2,
    :displayName           "Egyptian Pound",
    :numericCode           818,
    :symbol                "EGP"},
   "COU"
   {:currencyCode          "COU",
    :defaultFractionDigits 2,
    :displayName           "Colombian Real Value Unit",
    :numericCode           970,
    :symbol                "COU"},
   "ARS"
   {:currencyCode          "ARS",
    :defaultFractionDigits 2,
    :displayName           "Argentine Peso",
    :numericCode           32,
    :symbol                "ARS"},
   "MDL"
   {:currencyCode          "MDL",
    :defaultFractionDigits 2,
    :displayName           "Moldovan Leu",
    :numericCode           498,
    :symbol                "MDL"},
   "INR"
   {:currencyCode          "INR",
    :defaultFractionDigits 2,
    :displayName           "Indian Rupee",
    :numericCode           356,
    :symbol                "₹"},
   "ZWN"
   {:currencyCode          "ZWN",
    :defaultFractionDigits 2,
    :displayName           "ZWN",
    :numericCode           942,
    :symbol                "ZWN"},
   "CHE"
   {:currencyCode          "CHE",
    :defaultFractionDigits 2,
    :displayName           "WIR Euro",
    :numericCode           947,
    :symbol                "CHE"},
   "SAR"
   {:currencyCode          "SAR",
    :defaultFractionDigits 2,
    :displayName           "Saudi Riyal",
    :numericCode           682,
    :symbol                "SAR"},
   "PKR"
   {:currencyCode          "PKR",
    :defaultFractionDigits 2,
    :displayName           "Pakistani Rupee",
    :numericCode           586,
    :symbol                "PKR"},
   "TTD"
   {:currencyCode          "TTD",
    :defaultFractionDigits 2,
    :displayName           "Trinidad & Tobago Dollar",
    :numericCode           780,
    :symbol                "TTD"},
   "PTE"
   {:currencyCode          "PTE",
    :defaultFractionDigits 0,
    :displayName           "Portuguese Escudo",
    :numericCode           620,
    :symbol                "PTE"},
   "SKK"
   {:currencyCode          "SKK",
    :defaultFractionDigits 2,
    :displayName           "Slovak Koruna",
    :numericCode           703,
    :symbol                "SKK"},
   "NIO"
   {:currencyCode          "NIO",
    :defaultFractionDigits 2,
    :displayName           "Nicaraguan Córdoba",
    :numericCode           558,
    :symbol                "NIO"},
   "BND"
   {:currencyCode          "BND",
    :defaultFractionDigits 2,
    :displayName           "Brunei Dollar",
    :numericCode           96,
    :symbol                "BND"},
   "GHC"
   {:currencyCode          "GHC",
    :defaultFractionDigits 2,
    :displayName           "Ghanaian Cedi (1979–2007)",
    :numericCode           288,
    :symbol                "GHC"},
   "NAD"
   {:currencyCode          "NAD",
    :defaultFractionDigits 2,
    :displayName           "Namibian Dollar",
    :numericCode           516,
    :symbol                "NAD"},
   "FRF"
   {:currencyCode          "FRF",
    :defaultFractionDigits 2,
    :displayName           "French Franc",
    :numericCode           250,
    :symbol                "FRF"},
   "SVC"
   {:currencyCode          "SVC",
    :defaultFractionDigits 2,
    :displayName           "Salvadoran Colón",
    :numericCode           222,
    :symbol                "SVC"},
   "CHF"
   {:currencyCode          "CHF",
    :defaultFractionDigits 2,
    :displayName           "Swiss Franc",
    :numericCode           756,
    :symbol                "CHF"}}
  )
